# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1
      - image: mailhog/mailhog:v1.0.0
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test-integration
      - run: lein cloverage --codecov
      - run: bash <(curl -s https://codecov.io/bash)

  clj-kondo:
    docker:
      - image: borkdude/clj-kondo
    working_directory: ~/repo
    steps:
      - checkout
      - run: clj-kondo --lint src:test:integration

  cljstyle:
    docker:
      - image: circleci/clojure:lein-2.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check format by cljstyle
          command: |
            wget https://github.com/greglook/cljstyle/releases/download/0.12.1/cljstyle_0.12.1_linux.tar.gz
            tar -xf cljstyle_0.12.1_linux.tar.gz
            ./cljstyle check

workflows:
  version: 2
  build_and_test:
    jobs:
      - clj-kondo
      - cljstyle
      - build
