name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 0918nobita/setup-cljstyle@v0.4.0
        with:
          cljstyle-version: 0.15.0
      - run: cljstyle check --report -v

  clj_kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.10.19'
      - run: clj-kondo --lint src:test:integration

  test:
    needs: [clj_style, clj_kondo]
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.9.7'

      - name: Show versions
        run: |
          java -version
          lein version

      - name: Cache dependencies
        uses: toyokumo/cache@main
        with:
          path: |
            ~/.m2
            ~/.lein
          key: clj-cache-test-${{ hashFiles('project.clj') }}
          restore-keys: |
            clj-cache-test-

      - name: Run tests
        run: lein test-integration

      - name: Run cloverage
        run: |
          lein cloverage --codecov
          bash <(curl -s https://codecov.io/bash)
