name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cljstyle: latest
      - run: cljstyle check --report -v

  clj_kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          clj-kondo: latest
      - run: clj-kondo --lint src:test:integration



  test:
    needs: [clj_style, clj_kondo]
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master

      - name: Show versions
        run: |
          java -version

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
          key: clj-cache-test-${{ hashFiles('deps.edn') }}
          restore-keys: |
            clj-cache-test-

      - name: Run tests
        run: make test-integration

      - name: Upload reports
        uses: codecov/codecov-action@v4
